### ISSUE TITLE
JImmutableSet is not Serializable

### ISSUE THREAD

**Issue by AkexanderJunghans** [brianburton/java-immutable-collections#22]
I try to build classes that includes a JImmutableSet but this interface does not extends Serializable.
The implementation JImmutableHashSet does.
I have no chance of using JImmutableHashSet directly because the of() method gives me a JImmutableSet not a JImmutableHashSet. By now i can serialize a JImmutableSet because of the implenatation, but FindBugs complains.

Could you please make the  JImmutableSet extends Serializable.
Thank you for the great immutable collections I like so much.
Alexander Junghans

```
public class ImmutableSet<V> {
	private static final long serialVersionUID = 20200629L;

	private final JImmutableSet<V> set;

	private ImmutableSet(@Nonnull JImmutableSet<V> set) {
		this.set = set;
	}
}
```

Find Bugs: Class ImmutableSet defines non-transient non-serializable instance field set: JImmutableSet

This Serializable class defines a non-primitive instance field which is neither transient, Serializable, or java.lang.Object, and does not appear to implement the Externalizable interface or the readObject() and writeObject() methods.  Objects of this class will not be deserialized correctly if a non-Serializable object is stored in this field.

**Comment by brianburton** [comment]
That's very interesting.  In fact JImmutableSets are completely compatible with serialization via ObjectOutputStream.  I just didn't add Serializable on the base interfaces.  I suspect your class would serialize and deserialize even if findbugs isn't happy.  Have you tried that?

In the meantime I can add the inheritance to the interfaces.

**Comment by brianburton** [comment]
I have added Serializable to the base interfaces.  This is just in master for now but I plan a release in the next few weeks.

And thanks for the compliments on the classes!  I hope you find them useful!

**Comment by brianburton** [comment]
The v3.2.0 release includes Serializable on JImmutableSet and other collection interfaces.

**Comment by AkexanderJunghans** [comment]
Thanks for the improvement. I almost use only your collections because that's what make my work with treads so much easier.
So many things I don't have to worry about.
Thanks  ! Thumb up!

**Comment by brianburton** [comment]
Thanks @AkexanderJunghans !
